"""
Configuration package for Fake Offer Letter & Phishing Inspector.
"""

from .settings import (
    WEIGHT_DOMAIN_AGE_NEW,
    WEIGHT_FINANCIAL_KEYWORD,
    WEIGHT_WHOIS_MASKED,
    WEIGHT_EQUIPMENT_ADVANCE_FEE,
    WEIGHT_WEBMAIL_RECRUITER,
    WEIGHT_URGENCY_COERCION,
    THRESHOLD_CRITICAL,
    THRESHOLD_SUSPICIOUS,
    DOMAIN_AGE_THRESHOLD_DAYS,
    FINANCIAL_KEYWORDS,
    EQUIPMENT_PATTERNS,
    DEPOSIT_PATTERNS,
    URGENCY_PATTERNS,
    WEBMAIL_RECRUITER_PATTERN,
    PRIVACY_SIGNATURES,
    DEFAULT_MITRE_TAGS,
    SAMPLE_EQUIPMENT_SCAM,
    SAMPLE_SECURITY_DEPOSIT_SCAM,
    SAMPLE_LEGITIMATE_OFFER,
)

__all__ = [
    "WEIGHT_DOMAIN_AGE_NEW",
    "WEIGHT_FINANCIAL_KEYWORD",
    "WEIGHT_WHOIS_MASKED",
    "WEIGHT_EQUIPMENT_ADVANCE_FEE",
    "WEIGHT_WEBMAIL_RECRUITER",
    "WEIGHT_URGENCY_COERCION",
    "THRESHOLD_CRITICAL",
    "THRESHOLD_SUSPICIOUS",
    "DOMAIN_AGE_THRESHOLD_DAYS",
    "FINANCIAL_KEYWORDS",
    "EQUIPMENT_PATTERNS",
    "DEPOSIT_PATTERNS",
    "URGENCY_PATTERNS",
    "WEBMAIL_RECRUITER_PATTERN",
    "PRIVACY_SIGNATURES",
    "DEFAULT_MITRE_TAGS",
    "SAMPLE_EQUIPMENT_SCAM",
    "SAMPLE_SECURITY_DEPOSIT_SCAM",
    "SAMPLE_LEGITIMATE_OFFER",
]
